package by.htp.wa.command;

public enum CommandName {

	AUTHORIZATION, REGISTRATION, LOCALIZATION, SIGN_OUT, START_TEST, TEST_RESULT,

	GO_TO_SIGN_IN, GO_TO_MAIN, GO_TO_REGISTRATION, GO_TO_TEST

}
